version: '3.8'

services:
  # 1. Service untuk Frontend (Framework Web Rentopia)
  rentopia-web:
    build: .
    container_name: rentopia_frontend
    ports:
      - "5173:5173" # Membuka akses web di browser lewat localhost:5173
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:3000 # Menghubungkan ke API Backend nantinya
    depends_on:
      - db-rentopia

  # 2. Service untuk Database (PostgreSQL)
  db-rentopia:
    image: postgres:15-alpine
    container_name: rentopia_database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password_kamu # Ganti sesuai keinginan
      POSTGRES_DB: depokeretasbi     # Nama database sesuai proyekmu
    ports:
      - "5432:5432" # Port standar PostgreSQL
    volumes:
      - rentopia_db_data:/var/lib/postgresql/data

# Menyimpan data database agar tidak hilang saat kontainer dimatikan
volumes:
  rentopia_db_data: