DROP TABLE IF EXISTS product_views CASCADE;
DROP TABLE IF EXISTS likes CASCADE;
DROP TABLE IF EXISTS product_photos CASCADE;
DROP TABLE IF EXISTS products CASCADE;
DROP TABLE IF EXISTS users CASCADE;

CREATE TABLE products (
  id SERIAL PRIMARY KEY,
  visitor_id VARCHAR(100) NOT NULL,
  name VARCHAR(200) NOT NULL,
  category VARCHAR(100) NOT NULL,
  price INTEGER NOT NULL,
  location VARCHAR(200) NOT NULL,
  description TEXT,
  status VARCHAR(20) DEFAULT 'tersedia',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE product_photos (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  filename VARCHAR(255) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE likes (
  id SERIAL PRIMARY KEY,
  visitor_id VARCHAR(100) NOT NULL,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE (visitor_id, product_id)
);

CREATE TABLE product_views (
  id SERIAL PRIMARY KEY,
  product_id INTEGER NOT NULL REFERENCES products(id) ON DELETE CASCADE,
  viewer_visitor_id VARCHAR(100),
  viewed_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
